language: ruby
sudo: false
cache:
  directories:
    - workspace/redmine/vendor/bundle
addons:
  apt:
    packages:
      - ldap-utils
      - slapd
  chrome: stable
rvm:
 - 1.9.3
 - 2.3.6
env:
  global: REDMINE_DIR=./workspace/redmine
  matrix:
   - REDMINE=3.2-stable
   - REDMINE=3.3-stable
   - REDMINE=master
matrix:
  include:
   - rvm: 2.4.3
     env: REDMINE=3.4-stable
   - rvm: 2.4.3
     env: REDMINE=master
  exclude:
   - rvm: 1.9.3
     env: REDMINE=master
gemfile: workspace/redmine/Gemfile
bundler_args: --path vendor/bundle --gemfile workspace/redmine/Gemfile --without development rmagick
before_install:
 - ./script/ci.sh clone_redmine --target $REDMINE_DIR
 - cp ./config/database.yml.travis $REDMINE_DIR/config/database.yml
 - ./script/ci.sh install_plugin_gemfile
before_script:
 - mysql -e 'CREATE DATABASE redmine CHARACTER SET utf8;'
 - ./script/ci.sh prepare_redmine
 - ./script/ci.sh prepare_plugin
 - ./script/ci.sh start_ldap
 - 'phantomjs --webdriver 4444 2>&- 1>&- &'
script:
 - ./script/ci.sh run_tests
 - ./script/ci.sh test_uninstall
